// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"time"
	"webook-server/internal/repository"
	"webook-server/internal/repository/cache"
	"webook-server/internal/repository/dao"
	"webook-server/internal/service"
	"webook-server/internal/web"
	"webook-server/internal/web/middleware"
	"webook-server/ioc"
	"webook-server/pkg/jwt"
	"webook-server/pkg/ratelimit"
)

import (
	_ "github.com/spf13/viper/remote"
)

// Injectors from wire.go:

func InitWebServer(window2 time.Duration, rate2 int) *gin.Engine {
	cmdable := ioc.InitRedis()
	rateLimit := ratelimit.NewCacheSliceWindowLimiter(cmdable, window2, rate2)
	rateLimitMiddleware := middleware.NewRateLimitMiddleware(rateLimit)
	v := ioc.InitGinMiddlewares(rateLimitMiddleware)
	jwtHandler := jwt.NewCacheJWTHandler(cmdable)
	authMiddleware := middleware.NewAuthMiddleware(jwtHandler)
	db := ioc.InitDB()
	userDao := dao.NewUserDao(db)
	userCache := cache.NewUserCache(cmdable)
	userRepository := repository.NewUserRepository(userDao, userCache)
	userService := service.NewUserService(userRepository)
	codeCache := cache.NewCodeCache(cmdable)
	codeRepository := repository.NewCodeRepository(codeCache)
	smsService := ioc.InitSMSService()
	codeService := service.NewCodeService(codeRepository, smsService)
	userHandler := web.NewUserHandler(userService, codeService, jwtHandler)
	articleDAO := dao.NewArticleDao(db)
	articleCACHE := cache.NewArticleCache(cmdable)
	articleRepo := repository.NewArticleRepository(articleDAO, articleCACHE)
	articleService := service.NewArticleService(articleRepo)
	articleHandler := web.NewArticleHandler(articleService)
	engine := ioc.InitWebServer(v, authMiddleware, userHandler, articleHandler)
	return engine
}
