// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/web/middleware/auth.go
//
// Generated by this command:
//
//	mockgen -source=./internal/web/middleware/auth.go -package=middlewaremock -destination=./internal/web/middleware/mocks/auth_gen.go
//

// Package middlewaremock is a generated GoMock package.
package middlewaremock
