// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/jwt/cache.go
//
// Generated by this command:
//
//	mockgen -source=./pkg/jwt/cache.go -package=pkgmock -destination=./pkg/jwt/mock/cache_gen.go
//

// Package pkgmock is a generated GoMock package.
package pkgmock
